### ISSUE TITLE
Create React state management structure (Redux?)

### ISSUE THREAD

**Issue by admclamb** [online-community-builders/Chatter---frontend#1]
@baccarani We can also look into Zustand (another reducer based state management system)

**Comment by theodesp** [comment]
Before we agree on any use of State management I think we first need to establish we need it in the first place.
To make that decision we need to see which pages are we going to build and what are the data requirements.

I suggest we postpone this decision until we are sure that the benefits of an external state management library are justified.

Saying that, we also welcome ADR proposals documenting the whole research and reasoning behind any technical choice.

SEE:
https://okorkmaz.medium.com/adr-deep-dive-into-architecture-decision-records-8c110ce7d74e

**Comment by admclamb** [comment]
Yep that's a good point,
